In [50]:
import numpy as np   

## Creating Arrays in Numpy
# Creating an Array from a List

In [51]:
list1 = [10, 20,30]

In [52]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

# Using array to create an array
The difference between array and arrange is that array takes in a list and turns it into an array. Whereas arrange creates an array from a range of numbers.

In [53]:
arr2 = np.arange(10,20,1) #(start, Stop, Increment)
arr2


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Multidimensional arrays

### Combining two lists (2-D arrays)

When we combine arrays together, we can add dimensions. Comnbining two arrays gives us a 2-D array!
This creates a matrix for us on which we can perform matrix operations.

In [54]:
# lets create a new list to join the first list
list2 = [40,50,60]

# join the lists
list3 = [list1 + list2]

# create an array out of the joined list
arr3 = np.array(list3)
arr3

array([[10, 20, 30, 40, 50, 60]])

In [55]:
arr3.shape

(1, 6)

## 3-D arrays

In [56]:
arr3dim = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
arr3dim

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [57]:
arr3dim.shape

(2, 2, 3)

## Using Arrays and Scalars

Numpy arrays (ndarray) allows us to operform maxtrix operations.

In [58]:
# For example, we can use simple multiplication
arr3dim * 3

array([[[ 3,  6,  9],
        [ 9, 12, 15]],

       [[15, 18, 21],
        [21, 24, 27]]])

In [59]:
# How is this different than trying to do:
list1 * 3
# lists and arrays are treated differently as seen below:

[10, 20, 30, 10, 20, 30, 10, 20, 30]

In [60]:
# We can actually multiply an array with another arroay

# Create a new array with the same size as arr1
arr11 = np.array(list2)
# Multiply the arrays:
arr1 * arr11

array([ 400, 1000, 1800])

## Can we multiply arrays of different shapes?

The answer is NO

# Is it possible to multiply arrays of different dimensions? 
## Yes but they need to have the same size in one dimension

In [46]:
arr1 * arr3dim

array([[[ 10,  40,  90],
        [ 30,  80, 150]],

       [[ 50, 120, 210],
        [ 70, 160, 270]]])

# Task
## 10 minutes. Create ndarrays of the following sizes:
## One dimensional array with 12 elements (12,)
## Two dimensional array size (3, 4)
## Three dimensional array size (2, 5, 4)
## Check the size of your ndarray to ensure it is correct

In [61]:
onebytwelve = np.array[122,144,1]
threebyfour = np.array[5,18,22,1],[7,4,9,35],[12,13,14,15],[0,88,64,3]
twobyfivebyfour = np.array[[[1,2],[3,4],[5,6],[7,8],[9,10]],[[11,12],[13,14],[15,16],[17,18],[19,20]],[[21,22],[23,24],[25,26],[27,28],[29,30]],[[31,32],[33,34],[35,36],[37,38],[39,40]]]

TypeError: 'builtin_function_or_method' object is not subscriptable

### Accessing the values inside nd arrays
Lets use arr3 as an example

In [49]:
# How can we access a value?
# first call the array 
arr3

array([[10, 20, 30, 40, 50, 60]])

# To call an entry, index the element in the list 
## [row( from top down), column (left to right)] remember indexes start at zero
## Also more functions, please refer to the documentation

In [62]:
arr3.mean()

np.float64(35.0)

In [63]:
arr3.std()

np.float64(17.07825127659933)

# Iterating through ndarrays


In [64]:
# For a 1D array
for x in arr1:
    print(x)

10
20
30


In [65]:
# How about an n-dimensional array? Use nested loops
for dim in arr3:
    for num in dim:
        print(num)

10
20
30
40
50
60


In [66]:
# There is another way....nditer
#This can be used in simple scenarios, but also very complex ones
# It tends to be much cleaner for nested loops
for x in np.nditer(arr3):
    print(x)

10
20
30
40
50
60


### Saving and loading in numpy

In [67]:
# To save an array as a file
np.save("new",arr3)

In [68]:
# Load the file
np.load("new.npy")

array([[10, 20, 30, 40, 50, 60]])

In [70]:
# Saving as a txt
np.savetxt("new.txt", arr3, delimiter= ",")

In [72]:
# Loading a txt
np.loadtxt("new.txt", delimiter= ",")

array([10., 20., 30., 40., 50., 60.])